on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup
        run: echo test

  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: process
        run: |
          echo "process"
          date
          date
          uname -a
          echo ${{ github.ref }}
          git branch

  fail:
    runs-on: ubuntu-latest
    steps:
      - name: fail
        run: exit