name: test

on:
  workflow_dispatch


jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: process
        run: |
          echo "process"
          date
	  date
          uname -a
          echo ${{ github.ref }}
