name: test

on:
  workflow_dispatch


jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master

      - name: process
        run: |
          echo "process"
          date
          date
          uname -a
          echo ${{ github.ref }}
          git branch

