name: test

on:
  pull_request:
    branches:
      - master

jobs:
  call-child:
    uses: ./.github/workflows/child_workflow.yml

  main-job:
    needs: call-child
    runs-on: ubuntu-latest
    steps:
      - name: main
        run: echo main


   set_env_var:
    runs-on: ubuntu-latest
    outputs:
      user_specific_env: ${{ steps.set-var.outputs.user_env }}
    
    env:
      USER_MAP: |
        {
          "_takoika": "Valu1",
        }

    steps:
    - name: Check PR author and set env var
      id: set-var
      run: |
        USER_ENV=$(echo $USER_MAP | jq -r ".\"${{ github.event.pull_request.user.login }}\"")
        if [ -n "$USER_ENV" ]; then
          echo "::set-output name=user_env::$USER_ENV"
        else
          echo "::set-output name=user_env::DefaultValue"
        fi


  use_env_var:
    needs: set_env_var
    runs-on: ubuntu-latest
    env:
      USER_SPECIFIC_VALUE: ${{ needs.set_env_var.outputs.user_specific_env }}

    steps:
    - name: Use the user-specific env var
      run: |
        echo $USER_SPECIFIC_VALUE