name: test

on:
  pull_request:
    branches:
      - master

jobs:
  call-child:
    uses: .github/workflows/child_workflow.yml@23f824d8f02862b57c24e951684e33c3d7bcc0ea

  main-job:
    needs: call-child
    runs-on: ubuntu-latest
    steps:
      - name: main
        run: echo main